// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFKDCSuiRzJ39Il0qtfzaLAijkEVZBK0',
    appId: '1:909938235003:web:965d23db98faee343a74de',
    messagingSenderId: '909938235003',
    projectId: 'casa0015-b3b86',
    authDomain: 'casa0015-b3b86.firebaseapp.com',
    storageBucket: 'casa0015-b3b86.firebasestorage.app',
    measurementId: 'G-2FYL9W7N1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUbqYk825evVUzPcBXFDkjMSDo2Ynl04',
    appId: '1:909938235003:android:58cd1e02477bd3fb3a74de',
    messagingSenderId: '909938235003',
    projectId: 'casa0015-b3b86',
    storageBucket: 'casa0015-b3b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyq_wvfdsSIr0v4JomA12A-wJ4z9mr5fc',
    appId: '1:909938235003:ios:ad76415b06ad507c3a74de',
    messagingSenderId: '909938235003',
    projectId: 'casa0015-b3b86',
    storageBucket: 'casa0015-b3b86.firebasestorage.app',
    iosBundleId: 'com.soundscape.soundscapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyq_wvfdsSIr0v4JomA12A-wJ4z9mr5fc',
    appId: '1:909938235003:ios:ad76415b06ad507c3a74de',
    messagingSenderId: '909938235003',
    projectId: 'casa0015-b3b86',
    storageBucket: 'casa0015-b3b86.firebasestorage.app',
    iosBundleId: 'com.soundscape.soundscapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFKDCSuiRzJ39Il0qtfzaLAijkEVZBK0',
    appId: '1:909938235003:web:a372da4ac3f20b2f3a74de',
    messagingSenderId: '909938235003',
    projectId: 'casa0015-b3b86',
    authDomain: 'casa0015-b3b86.firebaseapp.com',
    storageBucket: 'casa0015-b3b86.firebasestorage.app',
    measurementId: 'G-3WQ5655N15',
  );
}
